# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ca1a532db4a0b2891e226581d573f843fa6b650b8d6a4569b5977ba3da46fc2c5346c412a0521096b50d5ef77e223c3d8505c46aa62a82ca7f55666d8654a9ea

test:
  secret_key_base: 10467d225b4f0a1a221ba444a582f77242380f4a8bbb34abb5b4a1129b145503ec26adfb684b1ad8e278874f8bf8cbca1b3b595df6cfc96c501ed32b2ac2daa7

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
